"""Freedesktop MIME defaults with per-entry, conditional restoration."""
import hashlib
import json
import os
from pathlib import Path
import re
import stat
import subprocess
import tempfile
import threading
from . import PLUGIN_ID
from .errors import Fault
from .files import FORMATS

DESKTOP_ID = PLUGIN_ID + ".desktop"
MARKER = "# Generated by " + PLUGIN_ID
MIMES = [v[0] for v in FORMATS.values()]


def read_text(path):
    try:
        st = path.lstat()
        if not stat.S_ISREG(st.st_mode) or st.st_uid != os.getuid() or st.st_size > 1024 * 1024:
            raise Fault("mime")
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""
    except (OSError, UnicodeError):
        raise Fault("mime") from None


def atomic_write(path, text, mode=0o600):
    path.parent.mkdir(parents=True, exist_ok=True)
    # Do not traverse user-config symlinks or overwrite an unrelated special file.
    for p in (path.parent, *path.parent.parents):
        if p.is_symlink():
            raise Fault("mime")
    if path.exists() or path.is_symlink():
        st = path.lstat()
        if not stat.S_ISREG(st.st_mode) or st.st_uid != os.getuid():
            raise Fault("mime")
        mode = stat.S_IMODE(st.st_mode)
    fd, temp = tempfile.mkstemp(prefix=".omadocs-", dir=path.parent)
    try:
        os.fchmod(fd, mode)
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            stream.write(text)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temp, path)
        dirfd = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(dirfd)
        finally:
            os.close(dirfd)
    finally:
        Path(temp).unlink(missing_ok=True)


def entry(text, mime):
    section = None
    found = []
    for line in text.splitlines():
        if line.strip().startswith("["):
            section = line.strip()
        elif section == "[Default Applications]" and line.split("=", 1)[0].strip() == mime and "=" in line:
            found.append(line.split("=", 1)[1].strip())
    if len(found) > 1:
        raise Fault("mime")
    return found[0] if found else None


def set_entry(text, mime, value):
    entry(text, mime)  # Reject ambiguous duplicate keys.
    lines = text.splitlines(keepends=True)
    section = None
    start = None
    end = len(lines)
    for index, line in enumerate(lines):
        if line.strip().startswith("["):
            if section == "[Default Applications]":
                end = index
                break
            section = line.strip()
            if section == "[Default Applications]":
                start = index
        elif section == "[Default Applications]" and "=" in line and line.split("=", 1)[0].strip() == mime:
            lines[index:index + 1] = [] if value is None else [mime + "=" + value + "\n"]
            return "".join(lines)
    if value is None:
        return text
    if start is None:
        return text + ("\n" if text and not text.endswith("\n") else "") + "[Default Applications]\n" + mime + "=" + value + "\n"
    lines.insert(end, mime + "=" + value + "\n")
    return "".join(lines)


def desktop_quote(value):
    if any(ord(c) < 32 or ord(c) == 127 for c in value):
        raise Fault("mime")
    # Desktop Entry string escaping is followed by Exec argument unquoting.
    value = value.replace("\\", "\\\\\\\\").replace('"', '\\"').replace("`", "\\`").replace("$", "\\$").replace("%", "%%")
    return '"' + value + '"'


class Mime:
    def __init__(self, paths, journal, root=None, query=None):
        self.paths, self.journal = paths, journal
        self.root = Path(root or Path(__file__).resolve().parent.parent)
        self.lock = threading.RLock()
        self.query_fn = query or self._query

    @staticmethod
    def _query(mime):
        try:
            value = subprocess.run(["xdg-mime", "query", "default", mime], check=True,
                                   capture_output=True, text=True, timeout=10).stdout.strip()
            if value and not re.fullmatch(r"[A-Za-z0-9._+-]+\.desktop", value):
                raise Fault("mime")
            return value
        except (OSError, subprocess.SubprocessError, UnicodeError):
            raise Fault("mime") from None

    def target(self):
        desktops = os.environ.get("XDG_CURRENT_DESKTOP", "").split(":")
        first = next((d.lower() for d in desktops if re.fullmatch(r"[A-Za-z0-9_-]+", d)), "")
        return self.paths.config / ((first + "-" if first else "") + "mimeapps.list")

    def backup(self, key):
        rows = self.journal.rows("SELECT value FROM mime_backup WHERE key=?", (key,))
        return json.loads(rows[0]["value"]) if rows else None

    def save(self, key, value):
        self.journal.execute("INSERT INTO mime_backup VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value", (key, json.dumps(value)))

    def status(self):
        with self.lock:
            return {"handlers": [{"extension": ext, "mime": spec[0], "current": self.query_fn(spec[0]),
                                   "installed": self.query_fn(spec[0]) == DESKTOP_ID} for ext, spec in FORMATS.items()],
                    "restoration_pending": bool(self.journal.rows("SELECT key FROM mime_backup"))}

    def generated(self):
        launcher = self.paths.bin / "omadocs"
        wrapper = "#!/usr/bin/python\n" + MARKER + "\nimport runpy\nrunpy.run_path(" + repr(str(self.root / "omadocs-run")) + ", run_name='__main__')\n"
        if self.root.parent.name == "runtime" and (self.root.parent.parent / ".omadocs-development-source").is_file():
            # Development installs replace the versioned runtime directory.
            # Resolve the current entry point at launch, not at MIME setup.
            wrapper = ("#!/usr/bin/python\n" + MARKER + "\nimport json, runpy\nfrom pathlib import Path\n"
                       "root = Path(" + repr(str(self.root.parent.parent)) + ")\n"
                       "manifest = json.loads((root / 'manifest.json').read_text())\n"
                       "entry = Path(manifest['entryPoints']['service'])\n"
                       "if manifest.get('id') != " + repr(PLUGIN_ID) + " or entry.is_absolute() or '..' in entry.parts:\n"
                       "    raise SystemExit('Invalid omadocs plugin entry point')\n"
                       "runpy.run_path(str(root / entry.parent / 'omadocs-run'), run_name='__main__')\n")
        desktop = (MARKER + "\n[Desktop Entry]\nType=Application\nName=omadocs\n"
                   "Comment=Upload a new Office copy to Google Drive; no synchronization\n"
                   "Exec=/usr/bin/python -I " + desktop_quote(str(launcher)) + " open -- %U\n"
                   "Terminal=false\nNoDisplay=true\nStartupNotify=false\n"
                   "Icon=" + str(self.root / "assets/omadocs.svg") + "\nMimeType=" + ";".join(MIMES) + ";\nCategories=Office;\n")
        return [(launcher, wrapper, 0o755), (self.paths.data / "applications" / DESKTOP_ID, desktop, 0o644)]

    def refresh_generated(self):
        """Repair owned launchers after an update without changing defaults."""
        with self.lock:
            for path, text, mode in self.generated():
                key = "generated:" + str(path)
                previous = self.backup(key)
                if previous is None or not path.exists() or path.is_symlink():
                    continue
                current = read_text(path)
                if hashlib.sha256(current.encode()).hexdigest() != previous["hash"] or current == text:
                    continue
                atomic_write(path, text, mode)
                self.save(key, {"path": str(path), "hash": hashlib.sha256(text.encode()).hexdigest()})

    def install(self):
        with self.lock:
            # Capture defaults before installing the desktop entry: it might
            # otherwise become the fallback when no explicit default existed.
            for mime in MIMES:
                if self.backup(mime) is None:
                    target = self.target()
                    self.save(mime, {"path": str(target), "entry": entry(read_text(target), mime),
                                     "effective": self.query_fn(mime), "existed": target.exists()})
            for path, text, mode in self.generated():
                key = "generated:" + str(path)
                previous = self.backup(key)
                if path.exists() or path.is_symlink():
                    current = read_text(path)
                    if previous is None or hashlib.sha256(current.encode()).hexdigest() != previous["hash"]:
                        raise Fault("mime")
                self.save(key, {"path": str(path), "hash": hashlib.sha256(text.encode()).hexdigest()})
                atomic_write(path, text, mode)
                os.chmod(path, mode)
            try:
                for mime in MIMES:
                    backup = self.backup(mime)
                    target = Path(backup["path"])
                    atomic_write(target, set_entry(read_text(target), mime, DESKTOP_ID + ";"))
                    if self.query_fn(mime) != DESKTOP_ID:
                        raise Fault("mime")
            except Exception:
                # Backups remain durable if rollback itself cannot complete.
                self.remove()
                raise Fault("mime") from None
            return self.status()

    def remove(self):
        with self.lock:
            for mime in MIMES:
                backup = self.backup(mime)
                if backup is None:
                    continue
                target = Path(backup["path"])
                text = read_text(target)
                current = entry(text, mime)
                if self.query_fn(mime) == DESKTOP_ID:
                    atomic_write(target, set_entry(text, mime, backup["entry"]))
                elif current is not None:
                    # A higher-priority default changed. Remove only our stale
                    # association; do not restore a previous default over it.
                    remaining = [x for x in current.split(";") if x and x != DESKTOP_ID]
                    if DESKTOP_ID in current.split(";"):
                        atomic_write(target, set_entry(text, mime, ";".join(remaining) + ";" if remaining else None))
                cleaned = read_text(target)
                if not backup["existed"] and cleaned.strip() == "[Default Applications]":
                    target.unlink(missing_ok=True)
                self.journal.execute("DELETE FROM mime_backup WHERE key=?", (mime,))
            for row in self.journal.rows("SELECT key,value FROM mime_backup WHERE key LIKE 'generated:%'"):
                value = json.loads(row["value"])
                path = Path(value["path"])
                if path.exists() and hashlib.sha256(read_text(path).encode()).hexdigest() == value["hash"]:
                    path.unlink()
                self.journal.execute("DELETE FROM mime_backup WHERE key=?", (row["key"],))
            return self.status()
